### ISSUE TITLE
Torguard API+Wireguard

### ISSUE THREAD

**Issue by HalianElf** [binhex/arch-int-vpn#17]
Torguard invalidates a wireguard config after 15 minutes of inactivity. They have an API that you can use to reactivate it. I'm trying to figure out a way to have the container run a curl to make sure the config is active when it tries bringing it up but I've run into two issues.

Wireguard has a `PreUp` command like the `PostUp` and `PostDown` you use for your scripts which is what it seems like I should use for this but it runs after the iptables are run so while the curl I need to do is hitting the wireguard port, it's using TCP and not UDP so it's attempting to get routed through the tunnel that's not up yet. So would it be possible to allow TCP as well as UDP to the VPN server IP?

The other issue I ran into (which was worked around easy enough through moving it to its own script instead) is, your sed to remove IPv6 is matching urls as well. I can deal with having the curl in its own script file but would be easier to just have it in the wireguard config so would it be possible to change that sed to match `[a-f]` instead of `[a-z]` since IPv6 is hex which would make the regex no longer match the `https:` of a url?

**Comment by binhex** [comment]
sorry for the delay, lots going on for me at the mo!. ok i saw your PR and merged it in, i will take a look at the other half of the issue.

**Comment by HalianElf** [comment]
All good. That one was an easy fix, I tried looking at the other but I'm not sure the best way to do it. For reference, the TorGuard API to reactivate is `https://${VPN_USER}:${VPN_PASS}@<WIREGUARD SERVER/PORT>/api/v1/setup?public-key=<PUBLIC KEY HTML ENCODED>`

**Comment by binhex** [comment]
> so while the curl I need to do is hitting the wireguard port, it's using TCP and not UDP so it's attempting to get routed through the tunnel that's not up yet. So would it be possible to allow TCP as well as UDP to the VPN server IP?

btw curl doesn't support UDP, and if its a web server you need to hit then it will have to be TCP, as HTTP(s) is TCP based, no idea why wireguard is attempting to send the request down a tunnel that isnt even established, that is odd!

**Comment by binhex** [comment]
another question, you say Torguard invalidates the wireguard config after 15 mins, does this not mean it IS valid for 15 mins after the tunnel is established?, or is it 'out of the box' not validated and needs to be activated in some manner before you can use it?.

**Comment by HalianElf** [comment]
When you generate the config from their site, it's active for 15 minutes. As long as you connect within that time, it's good until you disconnect (for more than 15 minutes) so if you are doing maintenance or something and take the container down for longer than that, the config is no longer active and you'll need to either generate a new config on the website or use that API call to reactivate your old one.

**Comment by binhex** [comment]
ok that makes sense, have you tried forcing curl to use a particular interface in your preup script, like so:-

```
curl --interface eth0 https://${VPN_USER}:${VPN_PASS}@<WIREGUARD SERVER/PORT>/api/v1/setup?public-key=<PUBLIC KEY HTML ENCODED>
```

**Comment by HalianElf** [comment]
I can try that. I think it was more that the iptables are already in place so the only thing being allowed outbound is UDP to the VPN port but I will let you know.

**Comment by binhex** [comment]
> I can try that. I think it was more that the iptables are already in place so the only thing being allowed outbound is UDP to the VPN port but I will let you know.

ahh i gotcha, ok i can relax that slightly, here is the line that needs changing (needs doing for each vpn container):-

https://github.com/binhex/arch-delugevpn/blob/e64b1efc09d3c37105a38d3e10bfb9b37fcaac90/run/root/iptable.sh#L93-L105

so this is where the iptable rule defines the protocol permitted, tbh i dont have a problem with dropping the protocol restriction, so i believe the code would look more like this:-

```
	# note grep -e is required to indicate no flags follow to prevent -A from being incorrectly picked up
	rule_exists=$(iptables -S | grep -e "-A INPUT -i "${docker_interface}"  --sport "${vpn_remote_port_list[$index]}" -j ACCEPT")
	if [[ -z "${rule_exists}" ]]; then
		# accept input to vpn gateway
		iptables -A INPUT -i "${docker_interface}" --sport "${vpn_remote_port_list[$index]}" -j ACCEPT
	fi
```
the same for the output rule too

**Comment by HalianElf** [comment]
Just confirmed, the connection just times out even specifying the interface.

And, yea looks like that would fix it.

**Comment by binhex** [comment]
which vpn image are you using?, i am going to create a test tagged version for you to test.

**Comment by HalianElf** [comment]
I'm using Deluge

**Comment by binhex** [comment]
ok a new 'test' tagged image has been produced, please pull down and give it a go.

**Comment by HalianElf** [comment]
Worked perfectly

**Comment by binhex** [comment]
> Worked perfectly

excellent news!, ok so the last part of the puzzle is how are you currently executing this?, via the PreUp as discussed earlier?, if so im assuming you are currently doing this by editing the wg0.conf file and adding in preup and defining a path to a script you wrote, am i correct?, how are you getting this to execute every 15 mins, while loop or some such with a sleep?.

**Comment by HalianElf** [comment]
It doesn't actually need to execute every 15 minutes. As long as you stayed connected, the connection stays active so it really only needs to run when the tunnel comes up. If it has to restart the tunnel, it wouldn't hurt to run it again but I would think having it in the `PreUp` would have it run if it has to restart.

All I ended up doing was adding this to the wg0.conf below the two lines you add:
`PreUp = curl -ks "https://${VPN_USER}:${VPN_PASS}@107.182.231.93:1443/api/v1/setup?public-key=somewhatredactedXmM5bJeP0TU4OORg7H%2BXsREE8%3D"`

**Comment by binhex** [comment]
Ahh right i see thanks for the details, it might come in handy if another Torguard user comes looking. ok in that case i think we are done on this task :-).

**Comment by binhex** [comment]
'latest' tagged image is now being built (should be done in about 30 mins), please switch back to latest at your convenience

**Comment by HalianElf** [comment]
Thanks!
