### ISSUE TITLE
Any way to use this as gluetun project

### ISSUE THREAD

**Issue by ShrirajHegde** [binhex/arch-int-vpn#38]
The [gluetun](https://github.com/qdm12/gluetun) project is great but it does not accept wireguard config and does not support domains in custom wireguard config.

I tried routing traffic through https://github.com/binhex/arch-qbittorrentvpn and it works as intended. Is there a way to make an image solely for this purpose so that any docker image can be routed through VPN using `network_mode: service:vpn`?

This seems like a better alternative.

**Comment by binhex** [comment]
Check out my privoxyvpn image, it is very lightweight whilst giving you socks proxy and HTTPS proxy out of the box all tunneled safely over VPN

**Comment by ShrirajHegde** [comment]
Alright, thanks, that seems great. Would be nice to add some keywords like 'gluetun alternative' for people searching.
